apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  strategy: { }
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      serviceAccountName: backend-sa
      containers:
        - image: ghcr.io/john4web/coffee-backend
          name: coffee-backend
          securityContext:
            readOnlyRootFilesystem: true # you cannot create files in the container's filesystem
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MONGODB_URI
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
