apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-deployment
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  strategy: { }
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: my-data
      containers:
        - image: mongo:7
          name: mongo
          volumeMounts:
            - name: my-data
              mountPath: /data/db
          ports:
            - containerPort: 27017
          resources: { }
