apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-mongodb
  name: my-mongodb
spec:
  containers:
  - image: mongo:7
    name: my-mongodb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
